version: "3.3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mysql-strapio
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-strapio:/var/lib/mysql

volumes:
  mysql-strapio:
